/* tslint:disable */
/* eslint-disable */
/**
 * Trados Cloud Platform API
 * The Trados Cloud Platform API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListLlmConfigurationsResponse,
} from '../models/index';

export interface ListLlmConfigurationsRequest {
    xLCTenant: string;
    authorization: string;
    fields?: string;
}

/**
 * 
 */
export class ConnectedAIApi extends runtime.BaseAPI {

    /**
     * List the account configured Large Language Models.
     * List LLM Configurations
     */
    async listLlmConfigurationsRaw(requestParameters: ListLlmConfigurationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLlmConfigurationsResponse>> {
        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling listLlmConfigurations().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling listLlmConfigurations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/connected-ai/llm-configurations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List the account configured Large Language Models.
     * List LLM Configurations
     */
    async listLlmConfigurations(requestParameters: ListLlmConfigurationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLlmConfigurationsResponse> {
        const response = await this.listLlmConfigurationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
