/* tslint:disable */
/* eslint-disable */
/**
 * Trados Cloud Platform API
 * The Trados Cloud Platform API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListPerfectMatchCandidatesResponse,
  PerfectMatchBatchMappingUpdateRequest,
  PerfectMatchCustomFileMappingRequest,
  PerfectMatchMappingCreateRequest,
  PerfectMatchMappingCreateResponse,
  PerfectMatchMappingResponse,
  PerfectMatchProjectFileMappingRequest,
} from '../models/index';

export interface AddPerfectMatchBatchMappingRequest {
    mappingId: string;
    authorization: string;
    xLCTenant: string;
    fields?: string;
    perfectMatchBatchMappingUpdateRequest?: PerfectMatchBatchMappingUpdateRequest;
}

export interface CreatePerfectMatchMappingRequest {
    authorization: string;
    xLCTenant: string;
    fields?: string;
    perfectMatchMappingCreateRequest?: PerfectMatchMappingCreateRequest;
}

export interface DeletePerfectMatchFileMappingForFileRequest {
    mappingId: string;
    batchMappingId: string;
    fileMappingId: string;
    targetLanguage: string;
    authorization: string;
    xLCTenant: string;
}

export interface GetPerfectMatchCandidatesRequest {
    mappingId: string;
    batchMappingId: string;
    fileMappingId: string;
    targetLanguage: string;
    authorization: string;
    xLCTenant: string;
    fields?: string;
}

export interface GetPerfectMatchMappingRequest {
    mappingId: string;
    authorization: string;
    xLCTenant: string;
    fields?: string;
}

export interface UpdatePerfectMatchBatchMappingRequest {
    mappingId: string;
    batchMappingId: string;
    authorization: string;
    xLCTenant: string;
    perfectMatchBatchMappingUpdateRequest?: PerfectMatchBatchMappingUpdateRequest;
}

export interface UpdatePerfectMatchFileMappingWithManuallyUploadedFileRequest {
    mappingId: string;
    batchMappingId: string;
    fileMappingId: string;
    authorization: string;
    xLCTenant: string;
    perfectMatchCustomFileMappingRequest?: PerfectMatchCustomFileMappingRequest;
}

export interface UpdatePerfectMatchFileMappingWithProjectFileRequest {
    mappingId: string;
    batchMappingId: string;
    fileMappingId: string;
    authorization: string;
    xLCTenant: string;
    perfectMatchProjectFileMappingRequest?: PerfectMatchProjectFileMappingRequest;
}

/**
 * 
 */
export class PerfectMatchMappingApi extends runtime.BaseAPI {

    /**
     * Adds a new PerfectMatch batch mapping.    When new source files are introduced to a mid-project, a new batch must be added to the current mapping to leverage PerfectMatch. This action triggers a background operation that identifies matching candidates for the newly added files.
     * Add PerfectMatch Batch Mapping
     */
    async addPerfectMatchBatchMappingRaw(requestParameters: AddPerfectMatchBatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectMatchMappingResponse>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling addPerfectMatchBatchMapping().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling addPerfectMatchBatchMapping().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling addPerfectMatchBatchMapping().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['perfectMatchBatchMappingUpdateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Adds a new PerfectMatch batch mapping.    When new source files are introduced to a mid-project, a new batch must be added to the current mapping to leverage PerfectMatch. This action triggers a background operation that identifies matching candidates for the newly added files.
     * Add PerfectMatch Batch Mapping
     */
    async addPerfectMatchBatchMapping(requestParameters: AddPerfectMatchBatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectMatchMappingResponse> {
        const response = await this.addPerfectMatchBatchMappingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * For more details on the PerfectMatch feature please consult the [official documentation](https://docs.rws.com/791595/1155478/trados-enterprise---accelerate/perfectmatch-general-information).    After creating a mapping, target files from the `matchingProjects` are automatically matched to the source files in the new project. This is a long-running background operation, and its `status` can be tracked by polling  the [Get PerfectMatch Mapping](../reference/Public-API.v1.json/paths/~1perfect-match-mappings~1{mappingId}/get) endpoint.
     * Create PerfectMatch Mapping
     */
    async createPerfectMatchMappingRaw(requestParameters: CreatePerfectMatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectMatchMappingCreateResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling createPerfectMatchMapping().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling createPerfectMatchMapping().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['perfectMatchMappingCreateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * For more details on the PerfectMatch feature please consult the [official documentation](https://docs.rws.com/791595/1155478/trados-enterprise---accelerate/perfectmatch-general-information).    After creating a mapping, target files from the `matchingProjects` are automatically matched to the source files in the new project. This is a long-running background operation, and its `status` can be tracked by polling  the [Get PerfectMatch Mapping](../reference/Public-API.v1.json/paths/~1perfect-match-mappings~1{mappingId}/get) endpoint.
     * Create PerfectMatch Mapping
     */
    async createPerfectMatchMapping(requestParameters: CreatePerfectMatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectMatchMappingCreateResponse> {
        const response = await this.createPerfectMatchMappingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a PerfectMatch file mapping for a specific file and target language.
     * Delete PerfectMatch File Mapping For a File
     */
    async deletePerfectMatchFileMappingForFileRaw(requestParameters: DeletePerfectMatchFileMappingForFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        if (requestParameters['batchMappingId'] == null) {
            throw new runtime.RequiredError(
                'batchMappingId',
                'Required parameter "batchMappingId" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        if (requestParameters['fileMappingId'] == null) {
            throw new runtime.RequiredError(
                'fileMappingId',
                'Required parameter "fileMappingId" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        if (requestParameters['targetLanguage'] == null) {
            throw new runtime.RequiredError(
                'targetLanguage',
                'Required parameter "targetLanguage" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling deletePerfectMatchFileMappingForFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings/{batchMappingId}/file-mappings/{fileMappingId}/target-languages/{targetLanguage}`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))).replace(`{${"batchMappingId"}}`, encodeURIComponent(String(requestParameters['batchMappingId']))).replace(`{${"fileMappingId"}}`, encodeURIComponent(String(requestParameters['fileMappingId']))).replace(`{${"targetLanguage"}}`, encodeURIComponent(String(requestParameters['targetLanguage']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a PerfectMatch file mapping for a specific file and target language.
     * Delete PerfectMatch File Mapping For a File
     */
    async deletePerfectMatchFileMappingForFile(requestParameters: DeletePerfectMatchFileMappingForFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePerfectMatchFileMappingForFileRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a list of file candidates that can be selected for PerfectMatch.
     * Get PerfectMatch Candidates
     */
    async getPerfectMatchCandidatesRaw(requestParameters: GetPerfectMatchCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPerfectMatchCandidatesResponse>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        if (requestParameters['batchMappingId'] == null) {
            throw new runtime.RequiredError(
                'batchMappingId',
                'Required parameter "batchMappingId" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        if (requestParameters['fileMappingId'] == null) {
            throw new runtime.RequiredError(
                'fileMappingId',
                'Required parameter "fileMappingId" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        if (requestParameters['targetLanguage'] == null) {
            throw new runtime.RequiredError(
                'targetLanguage',
                'Required parameter "targetLanguage" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling getPerfectMatchCandidates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings/{batchMappingId}/file-mappings/{fileMappingId}/target-languages/{targetLanguage}/candidates`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))).replace(`{${"batchMappingId"}}`, encodeURIComponent(String(requestParameters['batchMappingId']))).replace(`{${"fileMappingId"}}`, encodeURIComponent(String(requestParameters['fileMappingId']))).replace(`{${"targetLanguage"}}`, encodeURIComponent(String(requestParameters['targetLanguage']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves a list of file candidates that can be selected for PerfectMatch.
     * Get PerfectMatch Candidates
     */
    async getPerfectMatchCandidates(requestParameters: GetPerfectMatchCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPerfectMatchCandidatesResponse> {
        const response = await this.getPerfectMatchCandidatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the details of a PerfectMatch mapping.
     * Get PerfectMatch Mapping
     */
    async getPerfectMatchMappingRaw(requestParameters: GetPerfectMatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectMatchMappingResponse>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling getPerfectMatchMapping().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getPerfectMatchMapping().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling getPerfectMatchMapping().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the details of a PerfectMatch mapping.
     * Get PerfectMatch Mapping
     */
    async getPerfectMatchMapping(requestParameters: GetPerfectMatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectMatchMappingResponse> {
        const response = await this.getPerfectMatchMappingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a PerfectMatch batch mapping.    Pay special attention to how [updating works](https://languagecloud.sdl.com/lc/api-docs/updating-data-with-put).
     * Update PerfectMatch Batch Mapping
     */
    async updatePerfectMatchBatchMappingRaw(requestParameters: UpdatePerfectMatchBatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling updatePerfectMatchBatchMapping().'
            );
        }

        if (requestParameters['batchMappingId'] == null) {
            throw new runtime.RequiredError(
                'batchMappingId',
                'Required parameter "batchMappingId" was null or undefined when calling updatePerfectMatchBatchMapping().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling updatePerfectMatchBatchMapping().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling updatePerfectMatchBatchMapping().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings/{batchMappingId}`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))).replace(`{${"batchMappingId"}}`, encodeURIComponent(String(requestParameters['batchMappingId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['perfectMatchBatchMappingUpdateRequest'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a PerfectMatch batch mapping.    Pay special attention to how [updating works](https://languagecloud.sdl.com/lc/api-docs/updating-data-with-put).
     * Update PerfectMatch Batch Mapping
     */
    async updatePerfectMatchBatchMapping(requestParameters: UpdatePerfectMatchBatchMappingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePerfectMatchBatchMappingRaw(requestParameters, initOverrides);
    }

    /**
     * Updates a PerfectMatch file mapping with a manually uploaded file.
     * Update File Mapping With Manually Uploaded File
     */
    async updatePerfectMatchFileMappingWithManuallyUploadedFileRaw(requestParameters: UpdatePerfectMatchFileMappingWithManuallyUploadedFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling updatePerfectMatchFileMappingWithManuallyUploadedFile().'
            );
        }

        if (requestParameters['batchMappingId'] == null) {
            throw new runtime.RequiredError(
                'batchMappingId',
                'Required parameter "batchMappingId" was null or undefined when calling updatePerfectMatchFileMappingWithManuallyUploadedFile().'
            );
        }

        if (requestParameters['fileMappingId'] == null) {
            throw new runtime.RequiredError(
                'fileMappingId',
                'Required parameter "fileMappingId" was null or undefined when calling updatePerfectMatchFileMappingWithManuallyUploadedFile().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling updatePerfectMatchFileMappingWithManuallyUploadedFile().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling updatePerfectMatchFileMappingWithManuallyUploadedFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings/{batchMappingId}/file-mappings/{fileMappingId}/file`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))).replace(`{${"batchMappingId"}}`, encodeURIComponent(String(requestParameters['batchMappingId']))).replace(`{${"fileMappingId"}}`, encodeURIComponent(String(requestParameters['fileMappingId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['perfectMatchCustomFileMappingRequest'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a PerfectMatch file mapping with a manually uploaded file.
     * Update File Mapping With Manually Uploaded File
     */
    async updatePerfectMatchFileMappingWithManuallyUploadedFile(requestParameters: UpdatePerfectMatchFileMappingWithManuallyUploadedFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePerfectMatchFileMappingWithManuallyUploadedFileRaw(requestParameters, initOverrides);
    }

    /**
     * Updates a PerfectMatch file mapping with an existing target file from a PerfectMatch candidate. Only valid candidates can be used to request an update.    Use the [Candidates](../reference/Public-API.v1.json/paths/~1perfect-match-mappings~1{mappingId}~1batch-mappings~1{batchMappingId}~1file-mappings~1{fileMappingId}~1target-languages~1{targetLanguage}~1candidates/get) endpoint to retrieve a list of valid `fileId` and `projectId` to provide as matching data. 
     * Update File Mapping With Project File
     */
    async updatePerfectMatchFileMappingWithProjectFileRaw(requestParameters: UpdatePerfectMatchFileMappingWithProjectFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mappingId'] == null) {
            throw new runtime.RequiredError(
                'mappingId',
                'Required parameter "mappingId" was null or undefined when calling updatePerfectMatchFileMappingWithProjectFile().'
            );
        }

        if (requestParameters['batchMappingId'] == null) {
            throw new runtime.RequiredError(
                'batchMappingId',
                'Required parameter "batchMappingId" was null or undefined when calling updatePerfectMatchFileMappingWithProjectFile().'
            );
        }

        if (requestParameters['fileMappingId'] == null) {
            throw new runtime.RequiredError(
                'fileMappingId',
                'Required parameter "fileMappingId" was null or undefined when calling updatePerfectMatchFileMappingWithProjectFile().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling updatePerfectMatchFileMappingWithProjectFile().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling updatePerfectMatchFileMappingWithProjectFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/perfect-match-mappings/{mappingId}/batch-mappings/{batchMappingId}/file-mappings/{fileMappingId}/project-file`.replace(`{${"mappingId"}}`, encodeURIComponent(String(requestParameters['mappingId']))).replace(`{${"batchMappingId"}}`, encodeURIComponent(String(requestParameters['batchMappingId']))).replace(`{${"fileMappingId"}}`, encodeURIComponent(String(requestParameters['fileMappingId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['perfectMatchProjectFileMappingRequest'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a PerfectMatch file mapping with an existing target file from a PerfectMatch candidate. Only valid candidates can be used to request an update.    Use the [Candidates](../reference/Public-API.v1.json/paths/~1perfect-match-mappings~1{mappingId}~1batch-mappings~1{batchMappingId}~1file-mappings~1{fileMappingId}~1target-languages~1{targetLanguage}~1candidates/get) endpoint to retrieve a list of valid `fileId` and `projectId` to provide as matching data. 
     * Update File Mapping With Project File
     */
    async updatePerfectMatchFileMappingWithProjectFile(requestParameters: UpdatePerfectMatchFileMappingWithProjectFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePerfectMatchFileMappingWithProjectFileRaw(requestParameters, initOverrides);
    }

}
