/* tslint:disable */
/* eslint-disable */
/**
 * RWS Language Cloud API
 * The RWS Language Cloud public API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListPricingModelsResponse,
  PricingModel,
} from '../models/index';

export interface GetPricingModelRequest {
    pricingModelId: string;
    authorization: string;
    xLCTenant: string;
    fields?: string;
}

export interface ListPricingModelsRequest {
    authorization: string;
    xLCTenant: string;
    top?: number;
    skip?: number;
    location?: Array<string>;
    locationStrategy?: ListPricingModelsLocationStrategyEnum;
    sort?: string;
    fields?: string;
}

/**
 * 
 */
export class PricingModelApi extends runtime.BaseAPI {

    /**
     * Retrieves a pricing model by identifier.
     * Get Pricing Model
     */
    async getPricingModelRaw(requestParameters: GetPricingModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricingModel>> {
        if (requestParameters['pricingModelId'] == null) {
            throw new runtime.RequiredError(
                'pricingModelId',
                'Required parameter "pricingModelId" was null or undefined when calling getPricingModel().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getPricingModel().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling getPricingModel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/pricing-models/{pricingModelId}`.replace(`{${"pricingModelId"}}`, encodeURIComponent(String(requestParameters['pricingModelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves a pricing model by identifier.
     * Get Pricing Model
     */
    async getPricingModel(requestParameters: GetPricingModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricingModel> {
        const response = await this.getPricingModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a list of all the pricing models in an account.
     * List Pricing Models
     */
    async listPricingModelsRaw(requestParameters: ListPricingModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPricingModelsResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling listPricingModels().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling listPricingModels().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['top'] != null) {
            queryParameters['top'] = requestParameters['top'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['locationStrategy'] != null) {
            queryParameters['locationStrategy'] = requestParameters['locationStrategy'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/pricing-models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves a list of all the pricing models in an account.
     * List Pricing Models
     */
    async listPricingModels(requestParameters: ListPricingModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPricingModelsResponse> {
        const response = await this.listPricingModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListPricingModelsLocationStrategyEnum = {
    Location: 'location',
    Lineage: 'lineage',
    Bloodline: 'bloodline',
    Genealogy: 'genealogy'
} as const;
export type ListPricingModelsLocationStrategyEnum = typeof ListPricingModelsLocationStrategyEnum[keyof typeof ListPricingModelsLocationStrategyEnum];
