/* tslint:disable */
/* eslint-disable */
/**
 * Trados Cloud Platform API
 * The Trados Cloud Platform API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TranslationAddRequest,
  TranslationConcordanceSearchRequest,
  TranslationConcordanceSearchResponse,
  TranslationSearchRequest,
  TranslationSearchResponse,
  TranslationUnitAddUpdateResponse,
  TranslationUpdateRequest,
} from '../models/index';

export interface TranslationsAddRequest {
    authorization: string;
    xLCTenant: string;
    fields?: string;
    translationAddRequest?: TranslationAddRequest;
}

export interface TranslationsConcordanceSearchRequest {
    authorization: string;
    xLCTenant: string;
    fields?: string;
    translationConcordanceSearchRequest?: TranslationConcordanceSearchRequest;
}

export interface TranslationsLookupRequest {
    authorization: string;
    xLCTenant: string;
    fields?: string;
    translationSearchRequest?: TranslationSearchRequest;
}

export interface TranslationsUpdateRequest {
    authorization: string;
    xLCTenant: string;
    fields?: string;
    translationUpdateRequest?: TranslationUpdateRequest;
}

/**
 * 
 */
export class TranslationApi extends runtime.BaseAPI {

    /**
     * Adds a translation unit. The system identifies matching translation units in the TM based on the provided BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Add Translation Unit
     */
    async translationsAddRaw(requestParameters: TranslationsAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslationUnitAddUpdateResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling translationsAdd().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling translationsAdd().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/translations/translation-unit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['translationAddRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Adds a translation unit. The system identifies matching translation units in the TM based on the provided BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Add Translation Unit
     */
    async translationsAdd(requestParameters: TranslationsAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslationUnitAddUpdateResponse> {
        const response = await this.translationsAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Performs a concordance search for a given text within the TM linked to the specified translation engine. The translated content will be returned as a BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html) or [term](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Skeleton.Term.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Concordance
     */
    async translationsConcordanceSearchRaw(requestParameters: TranslationsConcordanceSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslationConcordanceSearchResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling translationsConcordanceSearch().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling translationsConcordanceSearch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/translations/concordance`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['translationConcordanceSearchRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Performs a concordance search for a given text within the TM linked to the specified translation engine. The translated content will be returned as a BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html) or [term](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Skeleton.Term.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Concordance
     */
    async translationsConcordanceSearch(requestParameters: TranslationsConcordanceSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslationConcordanceSearchResponse> {
        const response = await this.translationsConcordanceSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Translates a phrase in plain text or a BCM fragment containing a single segment. The translated content will be returned as a BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html) or [term](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Skeleton.Term.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Lookup
     */
    async translationsLookupRaw(requestParameters: TranslationsLookupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslationSearchResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling translationsLookup().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling translationsLookup().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/translations/lookup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['translationSearchRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Translates a phrase in plain text or a BCM fragment containing a single segment. The translated content will be returned as a BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html) or [term](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Skeleton.Term.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Lookup
     */
    async translationsLookup(requestParameters: TranslationsLookupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslationSearchResponse> {
        const response = await this.translationsLookupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a translation unit. The system identifies matching translation units in the TM based on the provided BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Update Translation Unit
     */
    async translationsUpdateRaw(requestParameters: TranslationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslationUnitAddUpdateResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling translationsUpdate().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling translationsUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/translations/translation-unit`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['translationUpdateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updates a translation unit. The system identifies matching translation units in the TM based on the provided BCM [fragment](https://developers.rws.com/languagecloud-api-docs/api/bcm/Sdl.Core.Bcm.BcmModel.Fragment.html).    For detailed concepts and examples see the [Translation API](../docs/translations/Translations.md) page.
     * Update Translation Unit
     */
    async translationsUpdate(requestParameters: TranslationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslationUnitAddUpdateResponse> {
        const response = await this.translationsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
