/* tslint:disable */
/* eslint-disable */
/**
 * Trados Cloud Platform API
 * The Trados Cloud Platform API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListTranslationServiceTypesResponse,
} from '../models/index';

export interface ListTranslationServiceTypesRequest {
    authorization: string;
    xLCTenant: string;
}

/**
 * 
 */
export class TranslationDomainApi extends runtime.BaseAPI {

    /**
     * List all available service types.
     * List Service Types
     */
    async listTranslationServiceTypesRaw(requestParameters: ListTranslationServiceTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTranslationServiceTypesResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling listTranslationServiceTypes().'
            );
        }

        if (requestParameters['xLCTenant'] == null) {
            throw new runtime.RequiredError(
                'xLCTenant',
                'Required parameter "xLCTenant" was null or undefined when calling listTranslationServiceTypes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xLCTenant'] != null) {
            headerParameters['X-LC-Tenant'] = String(requestParameters['xLCTenant']);
        }

        const response = await this.request({
            path: `/translation-domain/service-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List all available service types.
     * List Service Types
     */
    async listTranslationServiceTypes(requestParameters: ListTranslationServiceTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTranslationServiceTypesResponse> {
        const response = await this.listTranslationServiceTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
