name: Bump version

on:
  workflow_dispatch:
    inputs:
      newVersionType:
        description: "New version type"
        required: true
        # default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        id: bump-version
        # store new version variable, strip new line character and add to step output
        run: echo "NEW_VERSION = $(echo $(npm version ${{ github.event.inputs.newVersionType }} -m "Bump version to %s") | tr -d '\n')" >> "$GITHUB_OUTPUT"
      - name: Push latest version
        run: git push origin HEAD:main --follow-tags
      - name: Run publish and release workflow
        run: gh workflow run publish-and-release.yml --ref main -f version=${{ steps.bump-version.outputs.NEW_VERSION }}
        #run: |
        #  curl -L \
        #    -X POST \
        #    -H "Accept: application/vnd.github+json" \
        #    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        #    https://api.github.com/repos/${{github.repository_owner}}/${{github.repository}}/actions/workflows/publish-and-release.yml/dispatches \
        #    -d '{"ref":"main","inputs":{"version":"${{ steps.bump-version.outputs.NEW_VERSION }}"}}'
        # -H "X-GitHub-Api-Version: 2022-11-28" \

        #run: |
        #  curl -X POST \
        #    -H "Accept: application/vnd.github+json" \
        #    -H: "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        #    https://api.github.com/repos/${{github.repository}}/actions/workflows/publish-and-release.yml/dispatches \
        #    -d '{"ref": "main", "inputs": {"version": "${{ steps.bump-version.outputs.NEW_VERSION }}"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
