name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version type"
        required: true
        # default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump version
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}
      - name: Push latest version
        run: git push origin main --follow-tags
