name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-npm-package-to-github:
    name: Publish npm package to GitHub Packages
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt-hotspot"
          java-version: 11
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish npm package
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  create-github-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: publish-npm-package-to-github
    permissions:
      contents: write
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Create release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
