name: Trados UI Extensibility Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt-hotspot"
          java-version: "8"
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm run build
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
